- name: install ntp
  yum: 
    name: ['ntp','ntpdate']
    state: latest
- name: start ntp service
  service:
    name: ntp
    state: started
- name: configure the timezone
  shell: "ntpdate -s pool.ntp.org"



