- name: install apache
  yum:
    name: apache2
    state: latest

- name: create index2.html file
  file:
    path: /var/www/html
    mode: '0755'

- name: Simple Usage
  syslogger:
    msg: "Hello world!!"

- name: stop audit
  service:
    name: auditd
    state: stopped